from super_spider import SuperSpider
from selenium import webdriver
from selenium.webdriver import ActionChains
import time
dr=webdriver.Chrome()
dr.maximize_window()
dr.get('https://login.zhipin.com/')
dr.implicitly_wait(5)
dr.find_element_by_xpath('//*[@id="wrap"]/div[2]/div[1]/div[2]/div/form/div[1]/span[3]').click()
time.sleep(5)
dr.find_element_by_xpath('//*[@id="main"]/div[1]/div/dl[2]/dt/a').click()
dr.implicitly_wait(10)
time.sleep(1)
for i in range(1,10000,3):
	target = dr.find_element_by_xpath(f'//*[@id="recommend-list"]/div[1]/ul/li[{i}]')
	dr.execute_script("arguments[0].scrollIntoView();", target)
	time.sleep(1)
	for j in range(i,i+3):
		dr.find_element_by_xpath(f'//*[@id="recommend-list"]/div[1]/ul/li[{j}]/a').click()
		name=dr.find_element_by_xpath('/html/body/div[5]/div[2]/div[2]/div/div/div[1]/div[1]/div[2]/div[1]/h2/div').text
		print(name)
		dr.find_element_by_xpath('/html/body/div[5]/div[2]/div[2]/div/div/div[2]/div[1]/a/i').click()
		time.sleep(1)


# div = dr.find_element_by_id("nc_1_n1z")
# ActionChains(dr).click_and_hold(on_element=div).perform()
# time.sleep(0.15)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=300, yoffset=10).release().perform()
# div = dr.find_element_by_id("nc_2_n1z")
# ActionChains(dr).click_and_hold(on_element=div).perform()
# time.sleep(0.15)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=300, yoffset=10).release().perform()
# div = dr.find_element_by_id("nc_3_n1z")
# ActionChains(dr).click_and_hold(on_element=div).perform()
# time.sleep(0.15)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=300, yoffset=10).release().perform()
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=10, yoffset=10).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=30, yoffset=20).perform()
# time.sleep(0.5)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=70, yoffset=50).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=120, yoffset=50).release().perform()
# div = dr.find_element_by_id("nc_2_n1z")
# print(div)
# ActionChains(dr).click_and_hold(on_element=div).perform()
# time.sleep(0.15)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=10, yoffset=10).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=30, yoffset=20).perform()
# time.sleep(0.5)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=70, yoffset=50).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=120, yoffset=50).release().perform()
# div = dr.find_element_by_id("nc_3_n1z")
# print(div)
# ActionChains(dr).click_and_hold(on_element=div).perform()
# time.sleep(0.15)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=10, yoffset=10).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=30, yoffset=20).perform()
# time.sleep(0.5)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=70, yoffset=50).perform()
# time.sleep(1)
# ActionChains(dr).move_to_element_with_offset(to_element=div, xoffset=120, yoffset=50).release().perform()